meta_product_name: "Home-jitsu"
meta_title: "Home-Jitsu: Discover Brazilian Jiu-Jitsu near you."
meta_description: "This is your one-stop shop to find brazilian jiu-jitsu enthusiasts to build a community, host open-mats and connect with new partners."
meta_image: "cover.png"
twitter_account: "@lauragonzalezz"
